name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install specific npm version
      run: npm i -g npm@10

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint
